on: workflow_dispatch

run-name: Build Android APK

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
          add-to-path: true
          local-cache: true

      - name: Install aarch64-linux-android target
        run: rustup target add aarch64-linux-android

      - name: Install cargo-apk
        run: cargo install cargo-apk

      - name: Build shared library
        run: cargo apk build --lib --release

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/apk/milkshake-terminal.apk
